### PR TITLE
Update atlas files names, add AMU7T_registration.py script and update README.md

### PR DESCRIPTION
**Pull request by Nilser3**
1. In this PR we renamed the files:  `AMU7T_label_00_bin.nii.gz` -> `AMU7T_atlas_00_bin.nii.gz` . Because I noticed that sct_warp_template (sct v. 6.1) was generating labels with NearestNeighbor interpolation (see message).

```
WARP ATLAS OF WHITE MATTER TRACTS:

Dilate labels before warping...
Creating temporary folder (/tmp/sct_2024-02-20_11-45-40_apply-transfo-3d-label_n4qz4ea6)
/home/nilser/sct_6.1/bin/isct_antsApplyTransforms -d 3 -i /tmp/sct_2024-02-20_11-45-40_apply-transfo-3d-label_n4qz4ea6/dilated_data.nii -o label/atlas/AMU7T_label_00_bin.nii.gz -t test_2/warp_template2anat.nii.gz -r test_2/image_crop.nii.gz -n NearestNeighbor # in /home/nilser/registration/sub01
```

That was solved with the file name changes.

2. Also added a script in `code/AMU7T_registration.py` that regroups `sct_crop_image` , `sct_register_to_template ` , `sct_apply_transfo` , `sct_warp_template` for easier use. 

3. Also added information on README file for use this template.

### CODE REVIEW

**Comment by jcohenadad** [comment]
What is the purpose of this PR? What is the issue related to this PR?

Please provide a title less obscure than "Nl/amu7 tv3".

**Comment by Nilser3** [comment]
My bad for not being clear @jcohenadad 

1. In this PR we renamed the files:  `AMU7T_label_00_bin.nii.gz` -> `AMU7T_atlas_00_bin.nii.gz` . Because I noticed that sct_warp_template (sct v. 6.1) was generating labels with NearestNeighbor interpolation (see message).

```
WARP ATLAS OF WHITE MATTER TRACTS:

Dilate labels before warping...
Creating temporary folder (/tmp/sct_2024-02-20_11-45-40_apply-transfo-3d-label_n4qz4ea6)
/home/nilser/sct_6.1/bin/isct_antsApplyTransforms -d 3 -i /tmp/sct_2024-02-20_11-45-40_apply-transfo-3d-label_n4qz4ea6/dilated_data.nii -o label/atlas/AMU7T_label_00_bin.nii.gz -t test_2/warp_template2anat.nii.gz -r test_2/image_crop.nii.gz -n NearestNeighbor # in /home/nilser/registration/sub01
```

That was solved with the file name changes.

2. Also added a script in `code/AMU7T_registration.py` that regroups `sct_crop_image` , `sct_register_to_template ` , `sct_apply_transfo` , `sct_warp_template` for easier use. 

3. Also added information on README file for use this template.

**Comment by jcohenadad** [comment]
pls update the title:
image

title is used to generate automatic changelog reports

**Comment by jcohenadad** [comment]
pls update the PR body:

image

also see: https://intranet.neuro.polymtl.ca/onboarding/software-development.html#pr-body

**Pull request merged**
